### ISSUE TITLE
Comparison with clickhouse-obfuscator

### ISSUE THREAD

**Issue by alexey-milovidov** [nixys/nxs-data-anonymizer#1]
I've checked the README but didn't find the algorithm description.

I have a similar project: [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/tree/master/programs/obfuscator).

It is described here: https://github.com/ClickHouse/ClickHouse/tree/master/programs/obfuscator with implementation details, usage examples, and the motivation for the approach.

It will be nice to see a comparison!

**Comment by alexey-milovidov** [comment]
Thank you, and thanks for working on this project!

**Comment by borisershov** [comment]
Thanks! Good luck, Alexey! 🤝
