### ISSUE TITLE
1.7.0 creates SQL-syntax errors

### ISSUE THREAD

**Issue by hornpubmaster** [nixys/nxs-data-anonymizer#25]
Running the script creates SQL-syntax errors on MySQL dump. For example - quotes on date field dissapeared. Not present in 1.6.0 version, found in 1.7.0
before:
![image](https://github.com/nixys/nxs-data-anonymizer/assets/96118801/4024eaa7-690d-40be-8e0b-3835970295a9)
after:
![image](https://github.com/nixys/nxs-data-anonymizer/assets/96118801/795bd188-9515-48ec-b9c2-e553ac7152dc)

**Comment by borisershov** [comment]
Hi! Could you please show me a `show create table` for this table? Also I need to know a name of problem column

**Comment by hornpubmaster** [comment]
Hi! I think I should mention that "b_calendar_sharing_link" is not even used in yml config. Here is create table:
~~~~sql
CREATE TABLE `b_calendar_sharing_link` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OBJECT_ID` int(11) NOT NULL,
  `OBJECT_TYPE` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `HASH` char(64) COLLATE utf8_unicode_ci NOT NULL,
  `OPTIONS` text COLLATE utf8_unicode_ci,
  `ACTIVE` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  `DATE_CREATE` datetime NOT NULL,
  `DATE_EXPIRE` datetime DEFAULT NULL,
  `HOST_ID` int(11) DEFAULT NULL,
  `OWNER_ID` int(11) DEFAULT NULL,
  `CONFERENCE_ID` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PARENT_LINK_HASH` char(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CONTACT_ID` int(11) DEFAULT NULL,
  `CONTACT_TYPE` int(11) DEFAULT NULL,
  `MEMBERS_HASH` char(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FREQUENT_USE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ix_calendar_sharing_link_hash` (`HASH`),
  KEY `ix_calendar_sharing_link_object_id` (`OBJECT_ID`),
  KEY `ix_calendar_sharing_link_contact_id_contact_type` (`CONTACT_ID`,`CONTACT_TYPE`),
  KEY `ix_calendar_sharing_link_members_hash` (`MEMBERS_HASH`),
  KEY `ix_calendar_sharing_link_conference_id` (`CONFERENCE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
~~~~

**Comment by borisershov** [comment]
Hi! May you please also attach the rules from your config file for this table and column?

**Comment by hornpubmaster** [comment]
Hi again. As I mentioned, there are no rules in config for this table at all, yet data in it is still being modified

**Comment by borisershov** [comment]
Bug hasn't been confirmed
