### ISSUE TITLE
Mysql columns with no options are skipped

### ISSUE THREAD

**Issue by eeggenberger** [nixys/nxs-data-anonymizer#30]
A column in a CREATE TABLE statement that looks like this will be skipped:

```
  `body_summary` longtext,
```

Looks like dhCreateTableColumnAdd doesn't account for such cases, where there's just a type, but no options to it.

**Comment by borisershov** [comment]
Hi! Yes, the bug is confirmed. Thanks for the PR, but I think the best way to solve the issue is to switch to regex instead of string comparison. This bug will be fixed in next release
