### ISSUE TITLE
Add support for DOS line endings

### ISSUE THREAD

**Issue by eeggenberger** [nixys/nxs-data-anonymizer#32]
It seems like Mysql files with DOS line endings are not processed properly. I've worked around this by piping the files through `sed` and replacing \r\n with \n first, but it would be nice if files with DOS line endings would be supported out of the box.

**Comment by borisershov** [comment]
Hi! Could you please attach an example of that file?

**Comment by borisershov** [comment]
Hey! Issue has been confirmed

**Comment by borisershov** [comment]
Hi! This feature released in [v1.14.0](https://github.com/nixys/nxs-data-anonymizer/releases/tag/v1.14.0)
