### ISSUE TITLE
Whitespace sensitive parsing

### ISSUE THREAD

**Issue by akademic** [nixys/nxs-data-anonymizer#9]
I have two sql
```
INSERT INTO `my_table` (id, first_name, last_name) VALUES (1, 'John',NULL);
INSERT INTO `my_table` (id, first_name, last_name) VALUES (1, 'John', NULL);
```

First one produces value []byte("NULL") with type ValueTypeNULL
Second one []byte(" NULL") with type ValueTypeString

**Comment by borisershov** [comment]
Could you please specify a `mysqldump` version which creates a dumps with spaces? I mean this case:
```
INSERT INTO `my_table` (id, first_name, last_name) VALUES (1, 'John', NULL);
```

**Comment by akademic** [comment]
It is not mysqldump
I wrote this sql by hands

**Comment by borisershov** [comment]
This case may be solved with additional checks within the code. And it's affect to performance. So I don't think we need to fix this without real issue. I hope you are agree with me?

**Comment by akademic** [comment]
no problem
i can live with it
